workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-marathon

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/marathon
    tags: [ "latest", "0.5" ]
    when:
      branch: master
      event: push

plugin:
  name: Marathon
  desc: Publish applications to Mesos cluster through Marathon
  type: publish
  image: plugins/marathon
  labels:
    - mesos
    - marathon
    - cluster
    - docker
